SET Flowset(area,area,energy)                               
/                                                           
DK1                           .    Kasso .    Solar         
DK1                           .    Kasso .    Electricity   
DK1                           .    Kasso .    CO2           
DK1                           .    Kasso .    Water         
Kasso                         .    DK1   .    Electricity   
Kasso                         .    DK1   .    Heat          
Kasso                         .    DK1   .    StoredMethanol
Kasso                         .    DK1   .    Oxygen        
Kasso                         .    DK1   .    WaterOut      
                                                            
                                                            
                                                            
                                                            
                                                            
/;                                                          
