SET Location(area,tech)                       
/                                             
Kasso                   .    SolarPV          
Kasso                   .    Electrolysis     
Kasso                   .    MethanolSynthesis
Kasso                   .    ElectricStorage  
Kasso                   .    MethanolStorage  
Kasso                   .    DistilationTower 
                                              
                                              
                                              
                                              
                                              
                                              
/;                                            
                                              
                                              
