Table Techdata(tech,dataset)                                                                                                                     
*PARAMETER NAME              TECHDATA                                                                                                            
*INDICIES                    Tech     Dataset                                                                                                    
*TYPE                        ROW      COLUMN                                                                                                     
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
*                            %of X/h  X/h      %load/h  %x         %x           x hours    x hours       euro/ x                                 
                             Minimum  Capacity RampRate CapacityUP CapacityDown StorageCap InitialVolume VariableOmcost StartupCost              
SolarPV                               300                                                                0                                       
Electrolysis                 0.2      1.1      0.9      0.1        0.1                                   0              0                        
MethanolSynthesis            0.1      5                                                                  35             0                        
ElectricStorage                       1.6                                       1.6        1             0.08                                    
MethanolStorage                       880                                       880        0             0                                       
DistilationTower                      5                                                                  0.1                                     
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
